Urban/urls.py
# -*- coding: utf-8 -*-
"""Urban URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls import url,include,patterns
from django.contrib import admin
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # api
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('accounts.urls', namespace='accounts')),

    url(r'^', include('riddles.urls', namespace='riddles')),
    # url(r'^api/auth/token', obtain_jwt_token),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += patterns('',
                 (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes':True}),
            )

riddles/urls.py
# -*- coding: utf-8 -*-

"""Urban URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # riddles API
    #riddle/get_riddles_list?categories__name=ca3    włączone filtrowanie na pola
    url(r'api/get_riddles_list', views.RiddleListAPIView.as_view(), name='get_riddles_list_API'),

    url(r'api/get_riddle/(?P<pk>[0-9]+)', views.RiddleDetailAPIView.as_view(), name='get_riddle_API'),
    url(r'api/get_questions/(?P<riddle_pk>[0-9]+)',views.QuestionsListAPIView.as_view(), name='get_questions_list_API'),

    url(r'api/rate_riddle/(?P<pk>[0-9]+)/(?P<new_rate>[0-9]+)', views.RateRiddleAPI.as_view(), name='rate_riddle_API'),
    #api/get_near_riddles/?lat=32.0000&lon=11.000&my_range=10
    url(r'^api/get_near_riddles/$', views.NearRiddleListAPIView.as_view(), name='get_near_list'),

    # Riddles Normal Views
    url(r'^get_riddles_list$', views.riddle_list, name='riddle_list'),
    url(r'^$', views.riddle_list),
    #api/get_near_riddles?lat=32.0000&lon=11.000&my_range=10
    url(r'^get_near_riddles$', views.near_riddle_list, name='get_near_riddles'),
    url(r'^get_riddle/(?P<pk>[0-9]+)/', views.detail_riddle_view, name='get_riddle'),

    url(r'^questions_view/(?P<pk>[0-9]+)/', views.questions_view, name='questions'),

    # url(r'get_riddles_list', views.RiddleListView.as_view(), name='get_riddles_list'),

]

untitled5/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from UrbanExplorer import views

urlpatterns = [
    #url(r'^UrbanExplorer/', include('UrbanExplorer.urls')), // enables including external file

    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'), # function index in views.py
    url(r'venue/(?P<venue_id>[0-9]+)/$', views.venue, name='venue'),
    url(r'riddle/(?P<riddle_id>[0-9]+)/$', views.riddle, name='riddle'),
]

riddles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _

from django.db import models
import math

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=240)

    def __str__(self):
        return self.name

class Riddle(models.Model):
    name = models.CharField(
        _('name'),
        max_length=50,
    )

    description = models.TextField(
        _('description')
    )

    long = models.DecimalField(
        max_digits=9,
        decimal_places=6
    )
    lat = models.DecimalField(
        max_digits=9,
        decimal_places=6
    )
    times_resolved = models.DecimalField(
        max_digits=9,
        decimal_places=0,
        default=0
    )
    rate = models.DecimalField(
        max_digits=5,
        decimal_places=3,
        default=0
    )

    logo_image = models.ImageField(
        _('logo image'),
        upload_to='logos',
        null=True,
        blank=True
    )
    min_image = models.ImageField(
        _('min image'),
        upload_to='min_logos',
        null=True,
        blank=True
    )

    categories = models.ManyToManyField(Category)


    def __str__(self):
        return self.name

    def rate_riddle(self, rate):
        self.rate = (self.times_resolved * self.rate + int(rate)) / (self.times_resolved + 1)
        self.times_resolved += 1
        self.save()

    def distance(self, destination, my_range):
        lat1, lon1 = float(self.lat), float(self.long)
        lat2, lon2 = destination
        lat2, lon2=float(lat2), float(lon2)
        radius = 6371  # km

        dlat = math.radians(lat2 - lat1)
        dlon = math.radians(lon2 - lon1)
        a = math.sin(dlat / 2) * math.sin(dlat / 2) + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon / 2) * math.sin(dlon / 2)
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
        d = radius * c

        return d < float(my_range)

    # questions z klasy questions
    #     riddle_obj.question_set.all()
    #category z klasy Category


class Question(models.Model):
    riddle = models.ForeignKey(Riddle, db_index=True)

    question = models.CharField(max_length=240, db_index=True)
    answer = models.CharField(max_length=240)

    def __str__(self):
        return self.question

    def check_answer(self, given_ans):
        if given_ans.lower() == self.answer.lower():
            return True
        else:
            return False



class Images(models.Model):
    riddle = models.ForeignKey(Riddle, db_index=True)

    register_image = models.ImageField(
        _('register image'),
        upload_to='register_images',
        null=True,
        blank=True
    )

riddles/forms.py
# -*- coding: utf-8 -*-
from django import forms



class QuestionsForm(forms.Form):
    question_id = forms.IntegerField(widget=forms.HiddenInput)
    answer = forms.CharField(label='', widget=forms.TextInput, required=True)

    def __init__(self, *args, **kwargs):
        super(QuestionsForm, self).__init__(*args, **kwargs)
        if (kwargs.get('initial',False)):
            self.fields['answer'].label = kwargs['initial']['question_content']

from django.forms import formset_factory
QuestionsFormSet = formset_factory(QuestionsForm, extra=0)

riddles/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render

# Create your views here.

from rest_framework import generics, filters, views
from rest_framework.response import Response
from django.shortcuts import get_object_or_404,get_list_or_404
import django_filters

from .forms import *
from .models import *
from . import serializers


class RiddleFilter(filters.FilterSet,):
    categories = django_filters.CharFilter(name="categories__name")
    min_rate = django_filters.NumberFilter(name="rate", lookup_expr='gte')
    max_rate = django_filters.NumberFilter(name="rate", lookup_expr='lte')

    class Meta:
        model = Riddle
        fields = ['name','description','long','lat','times_resolved','categories','min_rate','max_rate']

#API VIEWS
class RiddleListAPIView(generics.ListAPIView):
    """Returns list of riddles with specific filters"""

    filter_backends = (filters.DjangoFilterBackend, filters.OrderingFilter, filters.SearchFilter )
    filter_class = RiddleFilter
    ordering_fields = ('rate', 'times_resolved')
    ordering = ('-times_resolved', )
    search_fields = ('name', 'description')

    serializer_class = serializers.RiddleSerializer

    def get_queryset(self):
        return Riddle.objects.all()




class NearRiddleListAPIView(RiddleListAPIView):
    """return list of riddles in range of given locations"""
    def get_queryset(self):
        request=self.request
        lat, lon, my_range = request.GET.get("lat"), request.GET.get("lon"), request.GET.get("my_range")
        if lat and lon and my_range:
            in_range_list = [t.id for t in Riddle.objects.all()
                             if t.distance((lat, lon), my_range)]
            return Riddle.objects.filter(id__in=in_range_list)
        else:
            return Riddle.objects.all()



class RiddleDetailAPIView(generics.RetrieveAPIView):
    """Returns chosen by id riddle"""

    serializer_class = serializers.RiddleSerializer

    def get_queryset(self):
        return Riddle.objects.all()


class QuestionsListAPIView(generics.ListAPIView):
    """returns all question with answers for specific riddle"""
    serializer_class = serializers.QuestionSerializer

    def get_queryset(self):
        return Question.objects.filter( riddle = self.kwargs['riddle_pk'] )


class RateRiddleAPI(views.APIView):
    """Rate riddle and calculate values"""

    def put(self, request, pk , new_rate):

        riddle = get_object_or_404(
            Riddle,
            id = pk
        )

        riddle.rate_riddle(int(new_rate))

        return Response({
            'status': 0,
        })

#Normal Views

def riddle_list(request):

    f = RiddleFilter(request.GET, queryset=Riddle.objects.all().order_by('-times_resolved'))
    return render(request, 'riddles/riddle_list.html', {'riddle_list': f})

def near_riddle_list(request):
    f = Riddle.objects.all()
    lat, lon, my_range = request.GET.get("lat"), request.GET.get("lon"), request.GET.get("my_range")
    order = request.GET.get("order")
    if lat and lon and my_range:
        in_range_list = [t.id for t in Riddle.objects.all()
                         if t.distance((lat, lon), my_range)]
        f.filter(id__in=in_range_list)

    f = RiddleFilter(request.GET, queryset=f)

    return render(request, 'riddles/riddle_list.html', {'riddle_list': f})

def detail_riddle_view(request, pk):

    riddle = get_object_or_404(
        Riddle,
        id=pk
    )

    photos = Images.objects.filter(riddle=pk)

    return render(request, 'riddles/riddle_detail.html', {'riddle': riddle,'images':photos,})

def start_riddle_view(request, pk):

    riddle = get_object_or_404(
        Riddle,
        id=pk
    )
    return render(request, 'riddles/riddle_map.html', {'riddle': riddle,})

def questions_view(request, pk):
    questions = Question.objects.filter(riddle=pk).order_by('pk')

    initial_data = []
    for question in questions:
        initial_data.append({
            "question_id": question.id,
            "question_content": question.question
        })
    if request.method == 'POST':
        formset = QuestionsFormSet( request.POST)
        if request.user.is_authenticated():
            for form in formset:
                if (request.POST.get(form.prefix + '-question_id')):
                    form.fields['answer'].widget.attrs['readonly'] = True

                    question_id = int(request.POST.get(form.prefix + '-question_id'))
                    answer = request.POST.get(form.prefix + '-answer')
                    question_obj = get_object_or_404(Question, id=question_id)
                    if not question_obj or not question_obj.check_answer(answer):
                        form.errors['answer'] = 'Niepoprawna odpowiedz'

                    else:
                        form.errors['answer'] = '+ 100pkt'
        return render(request, 'riddles/questions.html', {'questions': '', "forms": formset})

    if request.method == 'GET':
        formset = QuestionsFormSet(initial=initial_data)
        return render(request, 'riddles/questions.html', {'questions': questions,"forms":formset})

templates/riddles/map.html
{% extends "base.html" %}
{% block title %} List of all riddles {% endblock %}
{% block content %}

{% endblock %}

templates/riddles/questions.html
{% extends "base.html" %}
{% block title %} Questions {% endblock %}
{% block content %}

    <h1> Congratulations- you have found me!</h1>
    <span> Now, answer my questions for extra points!</span>
        <form method="POST" action="."> {% csrf_token %}
        {{ forms.management_form }}

            {% for question_form in forms %}

                {{ question_form.id }}
                <div class="question">
                {{ question_form.question_id }}
                    <h2>{{question_form.answer.label }}</h2>
                    <h3>{{question_form.answer }}</h3>
                </div>

                <span class="help-block">
                    {{ question_form.answer.errors }}
                </span>

            {%  endfor %}
            <input type='submit' value='Answer' class='btn btn-default'>
        </form>
{##}
{#    {% for question in question_list%}#}
{#        <div class="question">#}
{#             <h2>{{ question.title }}</h2>#}
{#             <h3>{{ question.text }}</h3>#}
{#        </div>#}
{#        <div class="answer">#}
{#            <label>Answer</label>#}
{#            <input type="text">#}
{#        </div>#}
{#    {% endfor %}#}


{% endblock %}

templates/riddles/riddle_detail.html
{% extends "base.html" %}
{% block title %}Riddle-{{ riddle.name }}{% endblock %}
{% block content %}

    <ul>
        <div><h1>{{ riddle.name }}</h1>
            {{ riddle.description }}<br>
            <img src="http://{{ request.META.HTTP_HOST }}/pic/{{ riddle.logo_image }}" width="200px" alt="Logo img">
            <br>  rate:{{ riddle.rate }}<br>

            Done {{ riddle.times_resolved }} times<br>
            {% for ca in  riddle.categories.all%}
                {{ ca.name}},
            {% endfor %}
        </div>
    {% for im in images %}
            <img src="http://{{ request.META.HTTP_HOST }}/pic/{{ im.register_image }}" width="200px" alt="registered img">

    {% endfor %}
    <br>
    <a href = "{% url 'riddles:questions' riddle.pk %}">Questions</a>

    </ul>

{% endblock %}

templates/riddles/riddle_list.html
{% extends "base.html" %}
{% block title %} List of all riddles {% endblock %}
{% block content %}

    <div class="row">

    <div id="search_block" class="panel-body">
        <form role="form" class="form-horizontal" method="post" action="">
            <div class="form-group">
                <label class="col-xs-2 col-sm-2 col-md-1 control-label" for="v_search">Search:</label>
                <div class="col-xs-8 col-sm-8 col-md-4">
                    <input type="text" placeholder="Enter Search Keywords" value="" name="v_search" id="v_search" class="form-control">
                </div>
                <div class="button-group col-xs-8 col-sm-8 col-md-2">
                    <button class="btn btn-primary" value="search" name="search" type="submit">Search</button>
                    <button class="btn btn-default" value="reset" name="reset" type="reset">Reset</button>
                </div>
            </div>
            <div class="form-group">
                <label class="col-xs-2 col-sm-2 col-md-1 control-label" for="filters">Filters:</label>
                <div class="col-xs-8 col-sm-8 col-md-2" id="filters">
                    <select class="form-control" name="section_id">
                        <option value="all">All Sections</option>
                        <option value="all">Test</option>
                    </select>
                </div>
                <div class="col-xs-8 col-sm-8 col-md-2">
                    <select class="form-control" name="category_id">
                        <option value="all">All Categories</option>
                        <option value="71">Test</option>
                    </select>
                </div>
            </div>

        </form>

    </div>
    <div class="row">
     {% for riddle in riddle_list%}
        <div class="page-header filled img-bg">
            <div class="overlay-bg">

            </div>
            <div class="row">
                <div class="col-md-3">
                    <h2><a href = "{% url 'riddles:get_riddle' riddle.pk %}">{{ riddle.name }}</a></h2>
                    <img src="http://{{ request.META.HTTP_HOST }}/pic/{{ riddle.logo_image }}" width="200px" alt="Logo img">
                </div>
                <div class="col-md-9">
                    <div class="row" style="padding-top: 20px;">
                        <div class="col-md-9" >
                            <p>{{ riddle.description }}</p>
                        </div>
                        <div class="col-md-3">
                            <ul class="list-page-breadcrumb">
                                <li>Rate : <strong>{{ riddle.rate }}</strong></li>
                                <li>Times resolved: <strong>{{ riddle.times_resolved }}</strong></li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                    <br>
                        <p><strong>
                            {% for ca in  riddle.categories.all%}
                                    {{ ca.name}}
                            {% endfor %}
                        </strong></p>
                    </div>
                </div>
            </div>
        </div>
     {% endfor %}
    </div>

{% endblock %}