Urban/urls.py
# -*- coding: utf-8 -*-
"""Urban URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls import url,include,patterns
from django.contrib import admin
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # api
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('accounts.urls', namespace='accounts')),

    url(r'^', include('riddles.urls', namespace='riddles')),
    # url(r'^api/auth/token', obtain_jwt_token),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += patterns('',
                 (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes':True}),
            )

accounts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib import admin

from .views import *

urlpatterns = [
    url(r'^api/login/$', UserLoginAPIView.as_view(), name='api_login'),
    url(r'^api/register/$', UserCreateAPIView.as_view(), name='api_register'),

    url(r'^accounts/profile/$', profile_view, name='profile'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
]

riddles/urls.py
# -*- coding: utf-8 -*-

"""Urban URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # riddles API
    #riddle/get_riddles_list?categories__name=ca3    włączone filtrowanie na pola
    url(r'api/get_riddles_list', views.RiddleListAPIView.as_view(), name='get_riddles_list_API'),

    url(r'api/get_riddle/(?P<pk>[0-9]+)', views.RiddleDetailAPIView.as_view(), name='get_riddle_API'),
    url(r'api/get_questions/(?P<riddle_pk>[0-9]+)',views.QuestionsListAPIView.as_view(), name='get_questions_list_API'),

    url(r'api/rate_riddle/(?P<pk>[0-9]+)/(?P<new_rate>[0-9]+)', views.RateRiddleAPI.as_view(), name='rate_riddle_API'),
    #api/get_near_riddles/?lat=32.0000&lon=11.000&my_range=10
    url(r'^api/get_near_riddles/$', views.NearRiddleListAPIView.as_view(), name='get_near_list'),

    # Riddles Normal Views
    url(r'^get_riddles_list$', views.riddle_list, name='riddle_list'),
    url(r'^$', views.riddle_list),
    #api/get_near_riddles?lat=32.0000&lon=11.000&my_range=10
    url(r'^get_near_riddles$', views.near_riddle_list, name='get_near_riddles'),
    url(r'^get_riddle/(?P<pk>[0-9]+)/', views.detail_riddle_view, name='get_riddle'),

    url(r'^questions_view/(?P<pk>[0-9]+)/', views.questions_view, name='questions'),

    # url(r'get_riddles_list', views.RiddleListView.as_view(), name='get_riddles_list'),

]

untitled5/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from UrbanExplorer import views

urlpatterns = [
    #url(r'^UrbanExplorer/', include('UrbanExplorer.urls')), // enables including external file

    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'), # function index in views.py
    url(r'venue/(?P<venue_id>[0-9]+)/$', views.venue, name='venue'),
    url(r'riddle/(?P<riddle_id>[0-9]+)/$', views.riddle, name='riddle'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Urban Explorer-{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>

    <div class="page-header">
        <h1><a href="/">Urban Explorer</a></h1>
    </div>
    {% include "navbar.html" %}
    <div class="content container">
        <div class="row">

            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

templates/login.html
{% extends "base.html" %}
{% block title %} Login {% endblock %}
{% block content %}
    {{ error }}
    Sign in with email or login
   <form action="." method="post">
    {% csrf_token %}
       <label for="username">Login: </label>
        <input id ="username" name="username"  type="text">
        <label for="email">Email: </label>
        <input id ="email" name="email" type="email">
        <label for="password">Password: </label>
        <input id ="password" name="password" type="password">

        <input type="submit" value="OK">
   </form>
{% endblock %}

templates/navbar.html
{% load staticfiles %}
<nav class="navbar navbar-inverse">
    {% block navbar %}
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'riddles:get_near_riddles' %}" ><img src="{% static 'images/icons/social1.png'%}" style="display: inline;  margin-right: -5px; width: 32px;">All Quests</a>
        </div>#3B5998
        <ul class="nav navbar-nav">
            <li><a href="{% url 'riddles:get_near_riddles' %}?min_rate=4"><img src="{% static 'src/img/fire.png'%}" style="display: inline; width:25px; "> Best Quests</a></li>
            <li><a href="{% url 'riddles:riddle_list' %}"><img src="{% static 'src/img/fire.png'%}" style="display: inline; width:25px; "> Trending</a></li>
        </ul>
        {% if user.user %}
            <div class="navbar-right">
                <a class="navbar-brand" href="{% url 'accounts:profile' %}"><img src="{% static 'images/icons/social1.png'%}" style="display: inline; width:25px; "> {{ user.user }} </a>
                <a class="navbar-brand" href="{% url 'accounts:logout' %}"><img src="{% static 'images/icons/social1.png'%}" style="display: inline; width:30px; "> Logout</a>
            </div>
        {% else %}
            <div class="navbar-right">
                <a class="navbar-brand active" href="{% url 'accounts:login' %}">Login</a>
                <a class="navbar-brand active" href="/register">Register</a>
            </div>
        {% endif %}
    </div>
    {% endblock %}
</nav>

templates/profile.html
{% extends "base.html" %}
{% block title %} {{ user.login }}- Profile {% endblock %}
{% block content %}
     <img class="profile-rounded" src="http://{{ request.META.HTTP_HOST }}/pic/{{ user.profile_picture }}" width="200px" alt="Logo img">
{#    -------------------------------------------^tak chyba nie można ale to sie sprawdzi potem#}
    <h2>{{ user.login }}</h2>
     <form method="POST" enctype="multipart/form-data" action="."> {% csrf_token %}
            {{ form }}
    <input type='submit' value='Submit' class='btn btn-default'>
    <h2 class="username">{{ user.name }}</h2>
    <h2>Stats</h2>
    <table>
        <tr>
            <td>Number of solved riddles :</td>
            <td>{{ user.solved_riddles.count  }}</td>
        </tr>
        <tr>
            <td>Points</td>
            <td>{{ user.experience }}</td>
        </tr>
        <tr>
            <td>Ranking place</td>
            <td>{{ user.ranking }}</td>
        </tr>
    <tr>
            <td>Level</td>
            <td>{{ user.lvl }}</td>
        </tr>
    </table>

{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block title %} Register {% endblock %}
{% block content %}

{% endblock %}